export const GREY_ISSUANCE_SQL = `SELECT
    MNGR, BUYER_ID, SO_TYPE, GREY_CLOSE_DATE, GREY_CLOSE_STATUS,
    SHIPMENT_CLOSE_DATE, SHIPMENT_CLOSE_STATUS, CNTRCT_NO,
    max(grey_issue_days) as grey_issue_days,
    SUM(I_QTY) AS I_QTY,
    SUM(I_VALUE) AS I_VALUE,
    ROUND(SUM(I_VALUE) / NULLIF(SUM(I_QTY), 0), 2) AS I_RATE,
    SUM(P_QTY) AS P_QTY,
    SUM(P_VALUE) AS P_VALUE,
    SUM(P_VALUE_ISS_QTY) AS P_VALUE_WRT_ISS,
    ROUND(SUM(P_VALUE) / NULLIF(SUM(P_QTY), 0), 2) AS P_RATE,
    ROUND(((SUM(I_QTY) / NULLIF(SUM(P_QTY), 0)) * 100) - 100, 2) AS iss_vs_plan_qty_prcnt,
    ROUND(
        ROUND(SUM(P_VALUE) / NULLIF(SUM(P_QTY), 0), 2) -
        ROUND(SUM(I_VALUE) / NULLIF(SUM(I_QTY), 0), 2),
    2) AS iss_vs_plan_rate_diff,
    ROUND(SUM(P_VALUE) - SUM(I_VALUE), 2) AS iss_vs_plan_value_diff
FROM KTMPL_AI.V_BASE_SUM t
GROUP BY
    MNGR, BUYER_ID, SO_TYPE, GREY_CLOSE_DATE, GREY_CLOSE_STATUS,
    SHIPMENT_CLOSE_DATE, SHIPMENT_CLOSE_STATUS, CNTRCT_NO`;
