GREY_ISSUANCE = """
SELECT
    MNGR, BUYER_ID, SO_TYPE, GREY_CLOSE_DATE, GREY_CLOSE_STATUS,
    SHIPMENT_CLOSE_DATE, SHIPMENT_CLOSE_STATUS, CNTRCT_NO,
    max(grey_issue_days) as grey_issue_days,
    SUM(I_QTY) AS I_QTY,
    SUM(I_VALUE) AS I_VALUE,
    ROUND(SUM(I_VALUE) / NULLIF(SUM(I_QTY), 0), 2) AS I_RATE,
    SUM(P_QTY) AS P_QTY,
    SUM(P_VALUE) AS P_VALUE,
    SUM(P_VALUE_ISS_QTY) AS P_VALUE_WRT_ISS,
    ROUND(SUM(P_VALUE) / NULLIF(SUM(P_QTY), 0), 2) AS P_RATE,
    ROUND(((SUM(I_QTY) / NULLIF(SUM(P_QTY), 0)) * 100) - 100, 2) AS iss_vs_plan_qty_prcnt,
    ROUND(
        ROUND(SUM(P_VALUE) / NULLIF(SUM(P_QTY), 0), 2) -
        ROUND(SUM(I_VALUE) / NULLIF(SUM(I_QTY), 0), 2),
    2) AS iss_vs_plan_rate_diff,
    ROUND(SUM(P_VALUE) - SUM(I_VALUE), 2) AS iss_vs_plan_value_diff
FROM KTMPL_AI.V_BASE_SUM t
GROUP BY
    MNGR, BUYER_ID, SO_TYPE, GREY_CLOSE_DATE, GREY_CLOSE_STATUS,
    SHIPMENT_CLOSE_DATE, SHIPMENT_CLOSE_STATUS, CNTRCT_NO
"""

PROCESSING = """
SELECT
    CNTRCT_NO, CNTRCT_DOCID, PRCS_ID, PRCS, MNGR_ID, BUYER_ID, PARTY_ID,
    LOT_COST_DATE, LOT_COST_DAYS, FLD_RCV_DATE, FLD_RCV_DAYS,
    SHIPPED_DATE, SHIPPED_DAYS, SHIPPED_QTY,
    LOT_MTRS, GREY_ISSUED, FOLD_RCV, LOT_COST,
    OVERHEAD_AMNT, DEPRICIATION_AMNT, POST_COST_AMNT, PRE_COST_AMNT,
    PRE_RATE, POST_RATE, POST_RATE_LOTMTRS, DIFF_RATE, DIFF_RATE_LOTMTRS
FROM KTMPL_AI.V_PROCESS_COST_COMPARISON
ORDER BY cntrct_no, prcs_id
"""

CUT_TO_PACK = """
select
    CNTRCT_NO, DOC_ID, CREATION_DATE, SET_ID, SET_NAME, SIZ, COLR, DSGN,
    REQ_SET, STICH_SET, PACK_SET, PACK_MTRS, SHIP_SET,
    PRE_RATE, POST_RATE,
    PACK_SET_PRE_AMNT, PACK_SET_POST_AMNT,
    PRE_ACC_VALUE, POST_ACC_VALUE,
    PRE_OVERHEAD as pre_oh_amt,
    0 as pre_dep_amt,
    STI_OH_MTR as post_oh_amt,
    STI_DPR_MTR as post_dep_amt
from ktmpl_ai.v_set_ship_summary_f
"""

YARN = """
SELECT CNTRCT_NO, YCOUNT, REQ_KGS, ISS_KGS, PRE_RATE, POST_RATE,
    PRE_AMNT, POST_AMNT, ISS_KGS * PRE_RATE AS ISS_PRE_AMNT, ISS_KGS * POST_RATE AS ISS_POST_AMNT
FROM KTMPL_AI.V_CNTRCT_YARN_SUMMARY
ORDER BY CNTRCT_NO, YCOUNT
"""

KNITTING = """
select CNTRCT_NO, QLTY, PRE_RATE, POST_RATE, REQ_KGS, KNIT_KGS, PRE_AMNT, POST_AMNT
from KTMPL_AI.F_KNIT_COMP_V
"""
