/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppPoRouteImport } from './routes/_app/po'
import { Route as AppCostingCutToPackRouteImport } from './routes/_app/costing/cut-to-pack'
import { Route as AppCostingGreyIssuanceRouteImport } from './routes/_app/costing/grey-issuance'
import { Route as AppCostingProcessingRouteImport } from './routes/_app/costing/processing'
import { Route as AppGarmentsKnittingRouteImport } from './routes/_app/garments/knitting'
import { Route as AppGarmentsYarnRouteImport } from './routes/_app/garments/yarn'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPoRoute = AppPoRouteImport.update({
  id: '/po',
  path: '/po',
  getParentRoute: () => AppRoute,
} as any)
const AppCostingCutToPackRoute = AppCostingCutToPackRouteImport.update({
  id: '/costing/cut-to-pack',
  path: '/costing/cut-to-pack',
  getParentRoute: () => AppRoute,
} as any)
const AppCostingGreyIssuanceRoute = AppCostingGreyIssuanceRouteImport.update({
  id: '/costing/grey-issuance',
  path: '/costing/grey-issuance',
  getParentRoute: () => AppRoute,
} as any)
const AppCostingProcessingRoute = AppCostingProcessingRouteImport.update({
  id: '/costing/processing',
  path: '/costing/processing',
  getParentRoute: () => AppRoute,
} as any)
const AppGarmentsKnittingRoute = AppGarmentsKnittingRouteImport.update({
  id: '/garments/knitting',
  path: '/garments/knitting',
  getParentRoute: () => AppRoute,
} as any)
const AppGarmentsYarnRoute = AppGarmentsYarnRouteImport.update({
  id: '/garments/yarn',
  path: '/garments/yarn',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/po': typeof AppPoRoute
  '/costing/cut-to-pack': typeof AppCostingCutToPackRoute
  '/costing/grey-issuance': typeof AppCostingGreyIssuanceRoute
  '/costing/processing': typeof AppCostingProcessingRoute
  '/garments/knitting': typeof AppGarmentsKnittingRoute
  '/garments/yarn': typeof AppGarmentsYarnRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/po': typeof AppPoRoute
  '/': typeof AppIndexRoute
  '/costing/cut-to-pack': typeof AppCostingCutToPackRoute
  '/costing/grey-issuance': typeof AppCostingGreyIssuanceRoute
  '/costing/processing': typeof AppCostingProcessingRoute
  '/garments/knitting': typeof AppGarmentsKnittingRoute
  '/garments/yarn': typeof AppGarmentsYarnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/po': typeof AppPoRoute
  '/_app/': typeof AppIndexRoute
  '/_app/costing/cut-to-pack': typeof AppCostingCutToPackRoute
  '/_app/costing/grey-issuance': typeof AppCostingGreyIssuanceRoute
  '/_app/costing/processing': typeof AppCostingProcessingRoute
  '/_app/garments/knitting': typeof AppGarmentsKnittingRoute
  '/_app/garments/yarn': typeof AppGarmentsYarnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/po'
    | '/costing/cut-to-pack'
    | '/costing/grey-issuance'
    | '/costing/processing'
    | '/garments/knitting'
    | '/garments/yarn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dashboard'
    | '/po'
    | '/'
    | '/costing/cut-to-pack'
    | '/costing/grey-issuance'
    | '/costing/processing'
    | '/garments/knitting'
    | '/garments/yarn'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/po'
    | '/_app/'
    | '/_app/costing/cut-to-pack'
    | '/_app/costing/grey-issuance'
    | '/_app/costing/processing'
    | '/_app/garments/knitting'
    | '/_app/garments/yarn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/po': {
      id: '/_app/po'
      path: '/po'
      fullPath: '/po'
      preLoaderRoute: typeof AppPoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/costing/cut-to-pack': {
      id: '/_app/costing/cut-to-pack'
      path: '/costing/cut-to-pack'
      fullPath: '/costing/cut-to-pack'
      preLoaderRoute: typeof AppCostingCutToPackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/costing/grey-issuance': {
      id: '/_app/costing/grey-issuance'
      path: '/costing/grey-issuance'
      fullPath: '/costing/grey-issuance'
      preLoaderRoute: typeof AppCostingGreyIssuanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/costing/processing': {
      id: '/_app/costing/processing'
      path: '/costing/processing'
      fullPath: '/costing/processing'
      preLoaderRoute: typeof AppCostingProcessingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/garments/knitting': {
      id: '/_app/garments/knitting'
      path: '/garments/knitting'
      fullPath: '/garments/knitting'
      preLoaderRoute: typeof AppGarmentsKnittingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/garments/yarn': {
      id: '/_app/garments/yarn'
      path: '/garments/yarn'
      fullPath: '/garments/yarn'
      preLoaderRoute: typeof AppGarmentsYarnRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppPoRoute: typeof AppPoRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCostingCutToPackRoute: typeof AppCostingCutToPackRoute
  AppCostingGreyIssuanceRoute: typeof AppCostingGreyIssuanceRoute
  AppCostingProcessingRoute: typeof AppCostingProcessingRoute
  AppGarmentsKnittingRoute: typeof AppGarmentsKnittingRoute
  AppGarmentsYarnRoute: typeof AppGarmentsYarnRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppPoRoute: AppPoRoute,
  AppIndexRoute: AppIndexRoute,
  AppCostingCutToPackRoute: AppCostingCutToPackRoute,
  AppCostingGreyIssuanceRoute: AppCostingGreyIssuanceRoute,
  AppCostingProcessingRoute: AppCostingProcessingRoute,
  AppGarmentsKnittingRoute: AppGarmentsKnittingRoute,
  AppGarmentsYarnRoute: AppGarmentsYarnRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
